### ISSUE TITLE
How to use pip install h3 on Windows

### ISSUE THREAD

**Issue by maxispeicher** [uber/h3-py#18]
Hey,
I´ve tried to install the h3 package by using pip install h3 on my windows machine. I have cmake, make and gcc installed. However cmake defaults to the Visual Studio compiler and therefore doesn´t create any make files. I´ve tried my best to fix this issue but I haven´t found a way to solve it yet.
Do you know any way how to use the pip install on a windows machine?

Many Thanks

**Comment by isaacbrodsky** [comment]
Thanks for reporting this. I haven't tried installing h3-py on a Windows system yet, but it looks like it should be possible by either setting https://github.com/uber/h3-py/blob/master/.install.sh to create makefiles, or invoking `cmake --build` instead of `make`.

I'm not sure on instructions for you to test that. We would probably need to add AppVeyor CI to the project to test the Windows install.

**Comment by moeppe-sp** [comment]
I´m not quite sure how to invoke the build process right after this step. I´ve already tried to tried to change the .intsall.sh file to create Makefiles and then the build process itself runs without error messages (which doesn´t seem to mean it runs at it should). Because then it runs into an error after make tht the file lib/libh3* doesn´t exist. (which is true after the build process)
So just for trying I´ve tried to swap lib/libh3* by bin/libh3* and after the shell script runs complete without any error. However no python package is created and if there is any further step I just don´t know how to continue from there.

**Comment by techshot25** [comment]
If you really want h3 on your windows machine without any problems, you can install everything related to your python environment inside a linux subsystem which may seem like a lot of work, but it allows you to utilize every piece of software that was built for linux and works exclusively for it. I simply moved my entire work to the linux subsystem and it has never failed me.

**Comment by MustaphaAmine** [comment]
Can you please tell me how to install h3 on Linux subsystem. because I've tried every possible way to install it on my windows machine but without success.

**Comment by ajfriend** [comment]
We just released v3.6.1, which should hopefully fix these install issues. Could you please try installing with `pip install h3==3.6.1` and let us know how it works?

**Comment by ajfriend** [comment]
Closing for now, please re-open if the issue is still there.

**Comment by chisomeluwa** [comment]
It still does not work on Windows @ajfriend, I get the error 
 _" note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h3
Failed to build h3
ERROR: Could not build wheels for h3, which is required to install pyproject.toml-based _projects"__

**Comment by ajfriend** [comment]
@chisomeluwa What versions of Python and pip are you using?

**Comment by chisomeluwa** [comment]
Python version - 3.10.0
Pip version - 22.0.3

**Comment by chisomeluwa** [comment]
Ok will try to install a lower version and let u know how it goes

**Comment by stareagle** [comment]
Will there be a solution for Python 3.10.x ?

**Comment by kylebarron** [comment]
There should be Python 3.10 wheels on the next release
